#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Build-time, public, and baked into the client bundle. Worker secrets do NOT
# go in here — they go through `put_secret` below, which hands them to
# Cloudflare and never writes them to disk.
ENV_FILE=".env"

DOMAIN="wallid.lol"
WEBHOOK_URL="https://${DOMAIN}/wall/webhook"

# ── helpers ───────────────────────────────────────────────────────────────

# Cloudflare Worker secrets set this run. Its own array rather than the
# library's `WRITTEN_SECRET`, which `finish` reports as GitHub secrets — these
# never touch GitHub, and a closing summary that says otherwise is a lie about
# where the live Stripe key ended up.
WORKER_SECRETS=()

# put_secret NAME VALUE — a Cloudflare Worker secret, via stdin so the value
# never appears in a process list or a shell history.
put_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | bunx wrangler secret put "$name" >/dev/null 2>&1; then
    WORKER_SECRETS+=("$name")
    printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Worker secret $name — run: bunx wrangler secret put $name")
    warn "could not set $name — is wrangler logged in?"
  fi
}

# random_hex — 32 bytes, for the values nobody should have to invent.
random_hex() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

banner "wallid in production"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "Everything below lands in one Cloudflare account: the Worker, the D1"
say "database, the R2 bucket, the Turnstile widget and the DNS."
printf '\n'

if [[ ! -f package.json ]] || ! grep -q '"name": "wallid"' package.json; then
  warn "run this from the wallid repo root"
  exit 1
fi

if bunx wrangler whoami 2>/dev/null | grep -qi "you are logged in"; then
  bunx wrangler whoami 2>/dev/null | grep -i "account" | head -3
else
  step "A browser window will open to authorise wrangler."
  bunx wrangler login || { warn "login failed"; exit 1; }
fi
printf '\n'
confirm "Is that the right Cloudflare account?" || {
  say "Run 'bunx wrangler logout', then start again."
  exit 0
}
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The database"
say "D1 holds the wall: every claim, every cell, every payment. It is the one"
say "piece of this that cannot be rebuilt from the repo."
printf '\n'

# The id in wrangler.jsonc is committed, so it may already be this account's or
# it may be somebody else's. Ask D1 rather than trusting the file.
if bunx wrangler d1 info wallid >/dev/null 2>&1; then
  note "a D1 database named 'wallid' already exists in this account"
else
  step "Creating it..."
  bunx wrangler d1 create wallid || warn "create failed — see the output above"
fi

DB_ID=$(bunx wrangler d1 info wallid --json 2>/dev/null \
  | grep -oE '"(uuid|database_id)"[[:space:]]*:[[:space:]]*"[0-9a-f-]{36}"' \
  | head -1 | grep -oE '[0-9a-f-]{36}')
if [[ -n "$DB_ID" ]]; then
  if grep -q "\"database_id\": \"$DB_ID\"" wrangler.jsonc; then
    note "wrangler.jsonc already points at it"
  else
    # Edited in place rather than asked for: a human pasting a UUID into JSON is
    # a typo waiting to happen, and the wrong id fails at runtime as an empty
    # wall rather than as an error.
    sed -i.bak -E "s/(\"database_id\": \")[^\"]*(\")/\1$DB_ID\2/" wrangler.jsonc && rm -f wrangler.jsonc.bak
    printf '  %s✓ wrote%s database_id into wrangler.jsonc\n' "$GREEN" "$RESET"
    warn "commit that change, or the next deploy from a clean clone misses it"
  fi
else
  warn "could not read the database id — put it in wrangler.jsonc by hand"
  SKIPPED+=("database_id in wrangler.jsonc")
fi

printf '\n'
step "Applying migrations to the remote database..."
bun run migrate || warn "migrations failed — see above"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The artwork bucket"
say "R2 holds what buyers upload. Keys are content hashes, so nothing in here"
say "is ever overwritten and nothing needs invalidating."
printf '\n'
if bunx wrangler r2 bucket list 2>/dev/null | grep -q "wallid-artwork"; then
  note "bucket 'wallid-artwork' already exists"
else
  bunx wrangler r2 bucket create wallid-artwork || warn "create failed — see above"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Turnstile — two values, and they are not interchangeable"
warn "This is the step most likely to go quietly wrong."
note "The SITE KEY is public and is compiled into the page at BUILD time."
note "The SECRET is a Worker secret, read at request time."
note "Set the secret but forget the site key and the widget runs on"
note "Cloudflare's test key, every token fails verification, and nobody can buy"
note "anything — with 'could not verify you are human' as the only clue."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Add a widget. Hostnames: ${DOMAIN} and www.${DOMAIN}"
step "Widget mode: Managed."
printf '\n'
ask BUN_PUBLIC_TURNSTILE_SITE_KEY "Paste the SITE key (0x4...):"
write_env BUN_PUBLIC_TURNSTILE_SITE_KEY "$BUN_PUBLIC_TURNSTILE_SITE_KEY"
ask_secret TURNSTILE_SECRET "Paste the SECRET key:"
put_secret TURNSTILE_SECRET "$TURNSTILE_SECRET"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The wall's own secrets"
say "Two values nobody should invent by hand, and one list."
printf '\n'

WALL_SECRET=$(random_hex)
put_secret WALL_SECRET "$WALL_SECRET"
note "the pepper for owner tokens — changing it later orphans every claim's"
note "proof of ownership, so it is generated once and never again"
printf '\n'

WALL_ADMIN_TOKEN=$(random_hex)
put_secret WALL_ADMIN_TOKEN "$WALL_ADMIN_TOKEN"
printf '  %sadmin token:%s %s\n' "$BOLD" "$RESET" "$WALL_ADMIN_TOKEN"
warn "copy that somewhere safe now — it is the bearer token for the"
warn "moderation endpoints and this is the only time it is shown."
printf '\n'
pause "Press Enter once you have saved the admin token"

say "The blocklist: comma-separated words refused in claim names."
note "Deliberately not in the repo — a public blocklist is a list of what is"
note "not blocked. Leave empty to set it later."
ask_secret WALL_BLOCKLIST "Blocklist (or Enter to skip):"
if [[ -n "$WALL_BLOCKLIST" ]]; then
  put_secret WALL_BLOCKLIST "$WALL_BLOCKLIST"
else
  SKIPPED+=("WALL_BLOCKLIST — bunx wrangler secret put WALL_BLOCKLIST")
fi
pause

# ── 5b ────────────────────────────────────────────────────────────────────
stage "The visitor count (optional)"
say "The chip on the wall that says how many people are here. The wall already"
say "counts them — every open tab beats against /wall/i — but reading the"
say "numbers back is an HTTP API, and that wants an account token."
printf '\n'
note "The token is an ACCOUNT token with 'Account Analytics: Read'. It can read"
note "every Analytics Engine dataset on the account, which is why it is a Worker"
note "secret and never a var in wrangler.jsonc."
note "Skip this and everything still works — /wall/pulse answers null and the"
note "chip simply does not appear."
printf '\n'

if confirm "Set up the visitor count now?"; then
  open_url "https://dash.cloudflare.com/?to=/:account/workers/analytics-engine"
  step "Enable Analytics Engine if it is not already — the deploy fails without"
  step "it, because wrangler.jsonc declares the PULSE binding."
  printf '\n'
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Create Token → Custom token → Permissions: Account · Account Analytics ·"
  step "Read. Scope it to this account only."
  printf '\n'
  ask PULSE_ACCOUNT_ID "Paste your Cloudflare ACCOUNT ID:"
  put_secret PULSE_ACCOUNT_ID "$PULSE_ACCOUNT_ID"
  ask_secret PULSE_READ_TOKEN "Paste the analytics READ token:"
  put_secret PULSE_READ_TOKEN "$PULSE_READ_TOKEN"
else
  SKIPPED+=("the visitor count — bunx wrangler secret put PULSE_ACCOUNT_ID, then PULSE_READ_TOKEN")
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Stripe — the live key"
warn "This one moves real money."
say "Everything the test wizard did to keep you out of live mode is inverted"
say "here: this stage wants sk_live_ and refuses sk_test_."
printf '\n'
open_url "https://dashboard.stripe.com/apikeys"
step "Check the toggle top-right does NOT say 'Test mode'."
step "Reveal the live secret key and copy it."
note "Live keys need an activated account: business details and a bank account."
printf '\n'
ask_secret STRIPE_SECRET_KEY "Paste the LIVE secret key (sk_live_...):"
while [[ ! "$STRIPE_SECRET_KEY" =~ ^(sk|rk)_live_ ]]; do
  if [[ "$STRIPE_SECRET_KEY" =~ ^(sk|rk)_test_ ]]; then
    warn "that is a TEST key. Production would take no money at all."
  else
    warn "expected a key starting sk_live_ (or a restricted rk_live_)"
  fi
  ask_secret STRIPE_SECRET_KEY "Paste the live secret key:"
done
put_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Deploy"
warn "DNS first, or this fails on a route conflict."
say "wrangler.jsonc claims ${DOMAIN} and www.${DOMAIN} as custom domains, and"
say "Cloudflare will not take a hostname that already has an A, AAAA or CNAME"
say "record on it."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/${DOMAIN}/dns/records"
step "Delete any A / AAAA / CNAME record on the apex and on www."
step "Leave MX and TXT alone — mail and verification are not affected."
printf '\n'
DNS_CLEAR=0
confirm "Are the apex and www clear of address records?" && DNS_CLEAR=1

if (( DNS_CLEAR )); then
  printf '\n'
  step "Building and deploying..."
  # `bun run deploy` is build + wrangler deploy, so the site key captured in
  # stage 4 is compiled in here.
  bun run deploy || warn "deploy failed — see the output above"
else
  SKIPPED+=("clear the DNS records, then run: bun run deploy")
  warn "skipping the deploy — clear them and run 'bun run deploy'"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Stripe — the webhook"
say "This is where a payment becomes cells. Without it, buyers are charged and"
say "the wall never hears: the claim sits pending and the cells stay unsold."
say "It comes after the deploy because Stripe verifies the URL answers."
printf '\n'
open_url "https://dashboard.stripe.com/webhooks"
step "Confirm you are in LIVE mode, then 'Add endpoint'."
step "Endpoint URL:  ${WEBHOOK_URL}"
step "Events to send: checkout.session.completed  — that one, and only that one."
step "Then reveal its signing secret and copy it."
printf '\n'
ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret (whsec_...):"
while [[ ! "$STRIPE_WEBHOOK_SECRET" =~ ^whsec_ ]]; do
  warn "expected a secret starting whsec_"
  ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret:"
done
put_secret STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"
note "secrets apply to the running Worker immediately — no redeploy needed"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "www to the apex"
say "Both hostnames now serve the site, which is a duplicate-content problem"
say "and splits every cache in the path. origin.ts names the apex as canonical,"
say "so www has to redirect to it — Cloudflare will not do that on its own."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/${DOMAIN}/rules/redirect-rules"
step "Create a rule. When: Hostname equals www.${DOMAIN}"
step "Then: Dynamic redirect → concat(\"https://${DOMAIN}\", http.request.uri.path)"
step "Status 301, and tick 'preserve query string'."
printf '\n'
confirm "Is the redirect rule live?" || SKIPPED+=("www → apex redirect rule")
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Check it is actually working"
say "Four things, and the fourth is the one that costs money to get wrong."
printf '\n'

printf '  %s· the site answers%s          ' "$BLUE" "$RESET"
curl -fsS -o /dev/null -w '%{http_code}\n' "https://${DOMAIN}/" || echo "FAILED"

printf '  %s· the wall index answers%s    ' "$BLUE" "$RESET"
curl -fsS "https://${DOMAIN}/wall/i" | head -c 60; printf '\n'

printf '  %s· www redirects to the apex%s ' "$BLUE" "$RESET"
curl -fsS -o /dev/null -w '%{http_code} → %{redirect_url}\n' "https://www.${DOMAIN}/" || echo "FAILED"

# The silent failure from stage 4, made loud: if the built bundle carries
# Cloudflare's test key instead of this account's, nobody can buy anything.
# Two conditions, and the second is the one that matters. Checking only that
# the real key is *present* is what let a bundle ship that had the key inlined
# beside a branch that threw it away and used the test key instead — the string
# was there, and the widget was still Cloudflare's test widget. When the real
# key is genuinely in use the test-key literal is dead code and disappears, so
# its absence is the honest signal.
printf '  %s· the real Turnstile key shipped%s ' "$BLUE" "$RESET"
if grep -rqs "$BUN_PUBLIC_TURNSTILE_SITE_KEY" dist/ 2>/dev/null &&
   ! grep -rqs "1x00000000000000000000AA" dist/ 2>/dev/null; then
  printf '%syes%s\n' "$GREEN" "$RESET"
else
  printf '%sNO — the page would run on the test widget%s\n' "$RED" "$RESET"
  SKIPPED+=("rebuild with BUN_PUBLIC_TURNSTILE_SITE_KEY set, then: bun run deploy")
fi

printf '\n'
say "Now the real one: buy a cell with a real card."
step "Drag out a single cell — it is \$1.00 — and pay."
step "Watch the cell appear on the wall. That is checkout, webhook and settle."
step "Then refund yourself from the Stripe dashboard if you want the dollar."
printf '\n'
if confirm "Did the cell appear?"; then
  printf '  %s✓ the whole path works in production%s\n' "$GREEN" "$RESET"
else
  warn "check, in order:"
  note "  - Stripe → the endpoint's recent deliveries: what status came back?"
  note "  - a 400 means the signing secret does not match the endpoint"
  note "  - a 404 'no such claim' means the deploy and the database disagree"
  note "  - bunx wrangler tail  — live logs from the running Worker"
  SKIPPED+=("verify a real purchase end to end")
fi

finish
(( ${#WORKER_SECRETS[@]} )) && note "set ${#WORKER_SECRETS[@]} Worker secret(s): ${WORKER_SECRETS[*]}"
printf '\n'
note "To swap Stripe modes later, two commands and no redeploy:"
note "  bunx wrangler secret put STRIPE_SECRET_KEY"
note "  bunx wrangler secret put STRIPE_WEBHOOK_SECRET"
printf '\n'
note "$ENV_FILE holds the public build-time key. It is needed by every future"
note "'bun run deploy' — a machine without it ships a wall nobody can buy from."
printf '\n'
