#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Worker secrets, not an `.env`. Wrangler reads this file and `server.ts` parses
# the same one; see `.dev.vars.example` and ADR 0002 for why the two are
# deliberately not the same file.
ENV_FILE=".dev.vars"

# Where the local server serves the webhook. `server.ts` defaults to 3000 and
# `worker/wall/index.ts` mounts the route under the `/wall/` prefix.
PORT="${PORT:-3000}"
WEBHOOK_PATH="localhost:${PORT}/wall/webhook"

banner "Stripe test mode for wallid"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The Stripe CLI"
say "Everything after this is easier with it: it prints a webhook signing"
say "secret without you visiting the dashboard, and it forwards live test"
say "events to the local server so a payment actually lands in the wall."
printf '\n'

if [[ ! -f package.json ]] || ! grep -q '"name": "wallid"' package.json; then
  warn "run this from the wallid repo root — .dev.vars belongs there"
  exit 1
fi

HAVE_CLI=0
if command -v stripe >/dev/null 2>&1; then
  HAVE_CLI=1
  note "found $(stripe --version 2>/dev/null | head -n1)"
else
  warn "the stripe CLI is not on PATH"
  say "Install one of these, then re-run:"
  step "macOS:  brew install stripe/stripe-cli/stripe"
  step "Linux:  see the install page (deb/rpm/tarball) — opening it now"
  step "or grab the binary from GitHub releases and put it on PATH"
  open_url "https://docs.stripe.com/stripe-cli#install"
  printf '\n'
  if confirm "Continue without it? (you'll copy the webhook secret by hand)"; then
    SKIPPED+=("install the Stripe CLI — needed to forward test events locally")
  else
    say "Nothing has been written. Re-run once the CLI is installed."
    exit 0
  fi
fi

# `.dev.vars` is gitignored and a fresh clone has none. Seeding from the example
# keeps the comments that explain each value, so the file this wizard edits
# still reads like the one in the repo.
if [[ ! -f "$ENV_FILE" && -f .dev.vars.example ]]; then
  # The empty placeholders come out on the way in. `ask_secret` offers whatever
  # is already in the file as the Enter-default, and a seeded KEY="" would
  # otherwise be offered back as the literal two characters `""`.
  grep -vE '^[A-Z_]+=""$' .dev.vars.example > "$ENV_FILE"
  printf '  %s✓ created%s %s from .dev.vars.example\n' "$GREEN" "$RESET" "$ENV_FILE"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign the CLI in"
if (( HAVE_CLI )); then
  say "This pairs the CLI with your Stripe account in the browser. It defaults"
  say "to test mode, which is the only mode this wizard touches."
  printf '\n'
  if stripe config --list 2>/dev/null | grep -q .; then
    note "the CLI already has a configured profile"
    if ! confirm "Sign in again anyway?"; then
      pause
      : # already paired
    else
      stripe login || warn "login failed — you can re-run 'stripe login' later"
    fi
  else
    step "A code will be printed; confirm it matches the one in the browser."
    stripe login || warn "login failed — you can re-run 'stripe login' later"
  fi
else
  note "skipped — no CLI"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The test secret key"
say "This is what the Worker calls Stripe with. Test mode only: a key that"
say "starts sk_test_ cannot move real money, whatever it is pointed at."
printf '\n'
open_url "https://dashboard.stripe.com/test/apikeys"
step "Check the toggle top-right says 'Test mode'."
step "On the 'Secret key' row, click 'Reveal test key', then copy it."
printf '\n'
ask_secret STRIPE_SECRET_KEY "Paste the secret key (sk_test_...):"

while [[ ! "$STRIPE_SECRET_KEY" =~ ^sk_test_ && ! "$STRIPE_SECRET_KEY" =~ ^rk_test_ ]]; do
  if [[ "$STRIPE_SECRET_KEY" =~ ^sk_live_ ]]; then
    # The one mistake here that costs real money, refused rather than warned.
    warn "that is a LIVE key. This wizard sets up test mode only."
  else
    warn "expected a key starting sk_test_ (or a restricted rk_test_ key)"
  fi
  ask_secret STRIPE_SECRET_KEY "Paste the test secret key:"
done
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The webhook signing secret"
say "The webhook is where a payment becomes cells, so the Worker verifies its"
say "signature before believing a word of it. This secret is that check."
printf '\n'

STRIPE_WEBHOOK_SECRET=""
if (( HAVE_CLI )); then
  say "Asking the CLI for the secret it will sign forwarded events with..."
  # --print-secret returns the local listener's secret without starting a
  # forwarder, which is exactly the value and nothing else.
  STRIPE_WEBHOOK_SECRET=$(stripe listen --print-secret 2>/dev/null | tr -d '[:space:]' || true)
  if [[ -n "$STRIPE_WEBHOOK_SECRET" ]]; then
    printf '  %s✓ got it%s from the CLI\n' "$GREEN" "$RESET"
  else
    warn "the CLI could not print one — falling back to the dashboard"
  fi
fi

if [[ -z "$STRIPE_WEBHOOK_SECRET" ]]; then
  open_url "https://dashboard.stripe.com/test/workbench/webhooks"
  step "Add a local listener, or open an existing test endpoint."
  step "Subscribe it to 'checkout.session.completed' — the only event read."
  step "Reveal its signing secret and copy it."
  ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret (whsec_...):"
fi

while [[ ! "$STRIPE_WEBHOOK_SECRET" =~ ^whsec_ ]]; do
  warn "expected a secret starting whsec_"
  ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret:"
done
write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"
note "this secret is tied to your machine's listener; it changes if you"
note "run 'stripe listen' under a different account."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The rest of .dev.vars"
say "Stripe is configured, but the checkout route needs three more values"
say "before it will take a payment at all."
printf '\n'

# A pepper, not a password: it salts the identity hashes, and changing it later
# orphans every owner token already issued.
if [[ -z "$(_existing WALL_SECRET || true)" || "$(_existing WALL_SECRET || true)" == '"a-development-pepper"' ]]; then
  GENERATED=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  write_env WALL_SECRET "$GENERATED"
  note "generated a random WALL_SECRET (32 bytes)"
else
  note "WALL_SECRET already set — left alone"
fi

# Cloudflare publishes this pair; it accepts any token, so the challenge is
# still verified for real without a Turnstile site of your own.
write_env TURNSTILE_SECRET "1x0000000000000000000000000000000AA"
note "TURNSTILE_SECRET set to Cloudflare's always-passes test secret"

if [[ -z "$(_existing WALL_ADMIN_TOKEN || true)" ]]; then
  write_env WALL_ADMIN_TOKEN "development"
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Buy a cell with a test card"
say "Two terminals, and the order matters more than it looks."
printf '\n'
warn "Start the forwarder BEFORE you pay."
note "It does not backfill. It forwards only events that happen while it is"
note "already connected, so an event from ten seconds before it started is one"
note "it will never mention — no error, no line in its log, just a payment that"
note "succeeded at Stripe and a wall that never heard. That is the single most"
note "common way this stage appears to fail."
printf '\n'
step "Terminal 1:  bun dev"
if (( HAVE_CLI )); then
  step "Terminal 2:  bun run stripe        (before paying, and leave it up)"
  note "               = stripe listen --forward-to $WEBHOOK_PATH"
else
  step "Terminal 2:  (install the CLI first — events cannot reach localhost)"
fi
printf '\n'
note "Only run one forwarder at a time on this account. A second one can take"
note "over the event stream, and the first keeps running while silently"
note "receiving nothing."
printf '\n'
step "Wait for the forwarder to print 'Ready!' — then open the wall."
step "Drag out a cell and fill in the panel."
step "Card 4242 4242 4242 4242 · any future expiry · any CVC · any postcode."
printf '\n'
note "Other cards worth knowing: 4000 0000 0000 9995 declines,"
note "4000 0025 0000 3155 asks for 3D Secure."
printf '\n'
pause "Press Enter once the forwarder says Ready! and bun dev is up"
open_url "http://localhost:${PORT}/"
printf '\n'
if confirm "Did the cell appear on the wall after paying?"; then
  printf '  %s✓ the whole path works: checkout, webhook, settle%s\n' "$GREEN" "$RESET"
else
  warn "check, in order:"
  note "  - did the forwarder print two lines for the payment?"
  note "      --> checkout.session.completed [evt_...]"
  note "      <-- [200] POST .../wall/webhook [evt_...]"
  note "    no first line  = it never received the event (started too late, or"
  note "                     a second forwarder has the stream)"
  note "    non-200 second = the wall refused it; the status says which check"
  note "  - .dev.vars is read by bun dev at startup, so restart it after this"
  note "    wizard wrote to it"
  printf '\n'
  note "To recover a payment whose event was missed:"
  note "  stripe events list --limit 5"
  note "  stripe events resend <evt_id>"
  SKIPPED+=("verify a test payment end to end")
fi

finish
note "Nothing here touches live mode. To go live, see the README's first-deploy"
note "steps — the same two names, set with 'wrangler secret put'."
printf '\n'
